.TH "CoreTestsDefaults" 3 "Fri Feb 4 2011" "cryomesh-cute" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreTestsDefaults \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CoreTestsDefaults.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~CoreTestsDefaults\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const std::string \fBTEST_DIRECTORY\fP = 'TestData/Tests/'"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBCoreTestsDefaults\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CoreTestsDefaults::~CoreTestsDefaults ()\fC [virtual]\fP"
.SS "CoreTestsDefaults::CoreTestsDefaults ()\fC [private]\fP"
.SH "Member Data Documentation"
.PP 
.SS "const std::string \fBCoreTestsDefaults::TEST_DIRECTORY\fP = 'TestData/Tests/'\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh-cute from the source code.
