.TH "cryomesh::components::ImpulseTest" 3 "Fri Feb 4 2011" "cryomesh-cute" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::components::ImpulseTest \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ImpulseTest.h>\fP
.PP
Inherits \fBICuteSuite\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImpulseTest\fP ()"
.br
.ti -1c
.RI "virtual \fB~ImpulseTest\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBrunSuite\fP ()"
.br
.ti -1c
.RI "static void \fBtestActivityCreation\fP ()"
.br
.ti -1c
.RI "static void \fBtestActivityMaxMin\fP ()"
.br
.ti -1c
.RI "static void \fBtestActiveCycles\fP ()"
.br
.ti -1c
.RI "static void \fBtestOperators\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cryomesh::components::ImpulseTest::ImpulseTest ()"
.SS "cryomesh::components::ImpulseTest::~ImpulseTest ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void cryomesh::components::ImpulseTest::runSuite ()\fC [static]\fP"Run all tests 
.SS "void cryomesh::components::ImpulseTest::testActiveCycles ()\fC [static]\fP"Test working with active cycles 
.SS "void cryomesh::components::ImpulseTest::testActivityCreation ()\fC [static]\fP"Test the creation of activity graphs 
.SS "void cryomesh::components::ImpulseTest::testActivityMaxMin ()\fC [static]\fP"Test getting activity max and mins 
.SS "void cryomesh::components::ImpulseTest::testOperators ()\fC [static]\fP"Test all operators 

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh-cute from the source code.
