.TH "cryomesh::common::MathsTest" 3 "Fri Feb 4 2011" "cryomesh-cute" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::common::MathsTest \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MathsTest.h>\fP
.PP
Inherits \fBICuteSuite\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMathsTest\fP ()"
.br
.ti -1c
.RI "virtual \fB~MathsTest\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBrunSuite\fP ()"
.br
.ti -1c
.RI "static void \fBtestGetRandomValue\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cryomesh::common::MathsTest::MathsTest ()"
.SS "cryomesh::common::MathsTest::~MathsTest ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void cryomesh::common::MathsTest::runSuite ()\fC [static]\fP"
.SS "void cryomesh::common::MathsTest::testGetRandomValue ()\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh-cute from the source code.
