.TH "cryomesh::components::ImpulseCollectionTest" 3 "Fri Feb 4 2011" "cryomesh-cute" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::components::ImpulseCollectionTest \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ImpulseCollectionTest.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBrunSuite\fP ()"
.br
.ti -1c
.RI "static void \fBtestAddRemoveImpulses\fP ()"
.br
.ti -1c
.RI "static void \fBtestClear\fP ()"
.br
.ti -1c
.RI "static void \fBtestGetActivity\fP ()"
.br
.ti -1c
.RI "static void \fBtestOperators\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Collection of tests for ImpulseCollection 
.SH "Member Function Documentation"
.PP 
.SS "void cryomesh::components::ImpulseCollectionTest::runSuite ()\fC [static]\fP"Run all tests 
.SS "void cryomesh::components::ImpulseCollectionTest::testAddRemoveImpulses ()\fC [static]\fP"Test adding and removing impulses 
.SS "void cryomesh::components::ImpulseCollectionTest::testClear ()\fC [static]\fP"Test clearing functions 
.SS "void cryomesh::components::ImpulseCollectionTest::testGetActivity ()\fC [static]\fP"Test activity calculation 
.SS "void cryomesh::components::ImpulseCollectionTest::testOperators ()\fC [static]\fP"Test operators 

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh-cute from the source code.
