.TH "cryomesh::common::ConnectorTest" 3 "Fri Feb 4 2011" "cryomesh-cute" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::common::ConnectorTest \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ConnectorTest.h>\fP
.PP
Inherits \fBICuteSuite\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConnectorTest\fP ()"
.br
.ti -1c
.RI "virtual \fB~ConnectorTest\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBrunSuite\fP ()"
.br
.ti -1c
.RI "static void \fBtestConnectDisconnect\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cryomesh::common::ConnectorTest::ConnectorTest ()"
.SS "cryomesh::common::ConnectorTest::~ConnectorTest ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void cryomesh::common::ConnectorTest::runSuite ()\fC [static]\fP"
.SS "void cryomesh::common::ConnectorTest::testConnectDisconnect ()\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh-cute from the source code.
