.TH "cryomesh::common::SimpleCollectionTest" 3 "Fri Feb 4 2011" "cryomesh-cute" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::common::SimpleCollectionTest \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SimpleCollectionTest.h>\fP
.PP
Inherits \fBICuteSuite\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SimpleCollectionTest\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBrunSuite\fP ()"
.br
.ti -1c
.RI "static void \fBtestAddRemove\fP ()"
.br
.ti -1c
.RI "static void \fBtestSum\fP ()"
.br
.ti -1c
.RI "static void \fBtestMaxMin\fP ()"
.br
.ti -1c
.RI "static void \fBtestGetValueAt\fP ()"
.br
.ti -1c
.RI "static void \fBtestInverseReverse\fP ()"
.br
.ti -1c
.RI "static void \fBtestOperators\fP ()"
.br
.ti -1c
.RI "static void \fBtestPad\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBSimpleCollectionTest\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cryomesh::common::SimpleCollectionTest::~SimpleCollectionTest ()\fC [virtual]\fP"Destructor 
.SS "cryomesh::common::SimpleCollectionTest::SimpleCollectionTest ()\fC [protected]\fP"Protected contructor to prevent initialisation 
.SH "Member Function Documentation"
.PP 
.SS "void cryomesh::common::SimpleCollectionTest::runSuite ()\fC [static]\fP"Run all tests 
.SS "void cryomesh::common::SimpleCollectionTest::testAddRemove ()\fC [static]\fP"Test adding and removing elements 
.SS "void cryomesh::common::SimpleCollectionTest::testGetValueAt ()\fC [static]\fP"Test getting value by index 
.SS "void cryomesh::common::SimpleCollectionTest::testInverseReverse ()\fC [static]\fP"test inverting and reversing 
.SS "void cryomesh::common::SimpleCollectionTest::testMaxMin ()\fC [static]\fP"Test getting maximum and minimum values 
.SS "void cryomesh::common::SimpleCollectionTest::testOperators ()\fC [static]\fP"Test all operators 
.SS "void cryomesh::common::SimpleCollectionTest::testPad ()\fC [static]\fP"Test padding collections 
.SS "void cryomesh::common::SimpleCollectionTest::testSum ()\fC [static]\fP"Test getting sum of all elements 

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh-cute from the source code.
