.TH "cryomesh::components::UseCaseImpulsePropagation" 3 "Fri Feb 4 2011" "cryomesh-cute" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::components::UseCaseImpulsePropagation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UseCaseImpulsePropagation.h>\fP
.PP
Inherits \fBICuteSuite\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~UseCaseImpulsePropagation\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBrunSuite\fP ()"
.br
.ti -1c
.RI "static void \fBtestPropagation\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBUseCaseImpulsePropagation\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Use case test of propagation from a Node, through a Connections and ending in a Node again 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual cryomesh::components::UseCaseImpulsePropagation::~UseCaseImpulsePropagation ()\fC [inline, virtual]\fP"
.SS "cryomesh::components::UseCaseImpulsePropagation::UseCaseImpulsePropagation ()\fC [inline, protected]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void cryomesh::components::UseCaseImpulsePropagation::runSuite ()\fC [static]\fP"Run all tests 
.SS "void cryomesh::components::UseCaseImpulsePropagation::testPropagation ()\fC [static]\fP"Test propagation through nodes and connections 

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh-cute from the source code.
