.TH "cryomesh::components::NodeTest" 3 "Fri Feb 4 2011" "cryomesh-cute" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryomesh::components::NodeTest \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NodeTest.h>\fP
.PP
Inherits \fBICuteSuite\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNodeTest\fP ()"
.br
.ti -1c
.RI "virtual \fB~NodeTest\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBrunSuite\fP ()"
.br
.ti -1c
.RI "static void \fBtestContruction\fP ()"
.br
.ti -1c
.RI "static void \fBtestUpdateImpulses\fP ()"
.br
.ti -1c
.RI "static void \fBtestEmitmpulse\fP ()"
.br
.ti -1c
.RI "static void \fBtestCheckActivation\fP ()"
.br
.ti -1c
.RI "static void \fBtestGetActivities\fP ()"
.br
.ti -1c
.RI "static void \fBtestGetSetCurrentActivity\fP ()"
.br
.ti -1c
.RI "static void \fBtestAddActivity\fP ()"
.br
.ti -1c
.RI "static boost::shared_ptr< \fBNodeTest\fP > \fBgetDefaultNode\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cryomesh::components::NodeTest::NodeTest ()"
.SS "cryomesh::components::NodeTest::~NodeTest ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "boost::shared_ptr< \fBNodeTest\fP > cryomesh::components::NodeTest::getDefaultNode ()\fC [static]\fP"
.SS "void cryomesh::components::NodeTest::runSuite ()\fC [static]\fP"
.SS "void cryomesh::components::NodeTest::testAddActivity ()\fC [static]\fP"
.SS "void cryomesh::components::NodeTest::testCheckActivation ()\fC [static]\fP"
.SS "void cryomesh::components::NodeTest::testContruction ()\fC [static]\fP"
.SS "void cryomesh::components::NodeTest::testEmitmpulse ()\fC [static]\fP"
.SS "void cryomesh::components::NodeTest::testGetActivities ()\fC [static]\fP"
.SS "void cryomesh::components::NodeTest::testGetSetCurrentActivity ()\fC [static]\fP"
.SS "void cryomesh::components::NodeTest::testUpdateImpulses ()\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for cryomesh-cute from the source code.
